print("shark")
print("bear")
print("cat")
print("dog")
primt("bird")
print("lion")
print("penguin")
print("monkey")
print("dinosaur")
print("tiger")
print("book")
print("werkbook")
print("notebook")
print("dragon")
print("elephant")
print("whale")
print("goa")
print("mariami")
print("goa best")
print ("chad")