favourite_food = input("enter your favorite food :")
userAge = int(input("enter your age :"))
user_name = input("enter your user name :")
friendAge = int(input("enter your friend age :"))
print(favourite_food)
print(userAge)
print(user_name)
print(friendAge)
